### ISSUE TITLE
UCLA Class Selector exits when entering "NONE" for classes

### ISSUE THREAD

**Issue by 0x65-e** [JOC9000/personal-projects#2]
If I enter "NONE" when prompted for my classes, the program quits instead of printing the classes I can take. I can just hit enter on an empty prompt, which works fine, but I get this weird output that doesn't look right:

> Let's see... so far you have taken 0 PHYSICS class(es), the following:
> PHYSICS

And when I do that, the resulting classes don't match what I expect. It just tells I can't take any classes, when I should be able to take CS 31 or Math 31A, for example.

**Comment by JOC9000** [comment]
Fix for this issue has been pushed to main. Implementation for input of "NONE" had not been finalized.

Further, made sure that classes with no prerequisites that have not been taken correctly show up as a class the user can take.
